// @ts-check
import tseslint from "typescript-eslint"

/**
 * ESLint flat-config (v10). Biome handles formatting + the fast
 * structural lints; this config is the **type-aware** complement that
 * Biome's TypeScript synthesiser cannot match yet (Biome v2.4 docs).
 *
 * Strict mode — every typescript-eslint preset's rule stays at its
 * default (`error`) severity. The few overrides below adapt to
 * project-specific conventions (we use `type` not `interface`, and a
 * couple of test-only deprecation warnings come from `expect-type`'s
 * internal API renaming).
 */
export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/coverage/**",
      "**/.wrangler/**",
      "**/.svelte-kit/**",
      "**/build/**",
      "**/.template/**",
      "**/.pnpm-home/**",
      "**/.pnpm-store/**",
      ".stryker-tmp/**",
      "packages/core/.stryker-tmp/**",
      "packages/core/reports/**",
      "apps/default/dist/**",
      // Plain JS / CJS config files outside the TypeScript projects.
      "eslint.config.js",
      "**/*.cjs",
      "**/*.config.cjs",
      "apps/web/svelte.config.js",
      "apps/web/vite.config.ts",
      "apps/web/vitest.config.ts",
      // Generated by `paraglide-js compile` — typed via .d.ts companions
      // and compiled out at build time; not part of the project tsconfig.
      "apps/web/src/paraglide/**",
      // Codegen scripts run via tsx outside the workspace tsconfig.
      "apps/default/scripts/**",
      // Service worker / static assets — not part of the SvelteKit
      // TS project graph; the worker runs in the browser SW global.
      "apps/web/static/**",
    ],
  },
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // We use `type` consistently (matches Effect's surface).
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      // Allow `_unused` parameters (common in Effect callbacks).
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  // Schema-mediated persistence gate (ADR-0019 / ADR-0059).
  // `apps/default/src/server/{adapters,durableObjects}/` is the
  // boundary where `tickets.payload` / `ticket_events.payload` round-
  // trip; the only legitimate `JSON.parse` and identifier-argument
  // `JSON.stringify` sites live under
  // `apps/default/src/server/adapters/codec/`. Object-literal
  // `JSON.stringify({...})` (structured logging) is explicitly OK.
  {
    files: [
      "apps/default/src/server/adapters/**/*.ts",
      "apps/default/src/server/durableObjects/**/*.ts",
    ],
    ignores: ["apps/default/src/server/adapters/codec/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "CallExpression[callee.object.name='JSON'][callee.property.name='parse']",
          message:
            "JSON.parse on storage payloads belongs in apps/default/src/server/adapters/codec/. Route ticket / event row deserialization through ./codec/ticketRowCodec.ts (decodeTicketRowPayload / decodeEventRowPayload / decodeTicketRowToEncoded).",
        },
        {
          selector:
            "CallExpression[callee.object.name='JSON'][callee.property.name='stringify'][arguments.0.type!='ObjectExpression']",
          message:
            "JSON.stringify on storage payloads belongs in apps/default/src/server/adapters/codec/. Object-literal stringify (structured logging) is OK; identifier / expression stringify of ticket / event payloads must go through ./codec/ticketRowCodec.ts.",
        },
      ],
    },
  },
)
