import { errorClassRegistry, errorToI18nKey } from "@booking/core"

/**
 * Phase 3 PR#8 — generate `docs/error-codes.md` from
 * `errorClassRegistry`. Drift-gated by `just gen-error-docs` plus
 * `git diff --exit-code -- docs/error-codes.md` so adding a new
 * `Schema.TaggedErrorClass` to the registry forces a docs refresh
 * in the same commit, and the generated table is the canonical
 * single-source-of-truth surface for all 33 tags.
 *
 * Categorisation rule — the registry is structurally ordered as
 * Validation (17) → Domain (13) → Infrastructure (3). Each entry's
 * static `severity` matches its category, so the table groups by
 * severity directly without re-listing the static order.
 */

type ErrorRow = {
  readonly tag: string
  readonly code: string
  readonly severity: "validation" | "domain" | "infrastructure"
  readonly i18nKey: string
}

/**
 * The factory `Schema.TaggedErrorClass(TAG, ...)` does not expose
 * the literal `TAG` as a class-side static, but every registered
 * class is named `<TAG>Error` by convention. Strip the `Error`
 * suffix to recover the tag — the `errorClassRegistry` ordering plus
 * the convention is the categorical contract that lets this hold.
 */
const tagOf = (cls: (typeof errorClassRegistry)[number]): string => {
  const name = (cls as { readonly name: string }).name
  return name.endsWith("Error") ? name.slice(0, -"Error".length) : name
}

const rows: readonly ErrorRow[] = errorClassRegistry.map((cls) => {
  const tag = tagOf(cls)
  const code = (cls as { readonly code: string }).code
  const severity = (cls as { readonly severity: "validation" | "domain" | "infrastructure" })
    .severity
  const i18nKey = errorToI18nKey({ _tag: tag } as never) as unknown as string
  return { tag, code, severity, i18nKey }
})

const renderTable = (subset: readonly ErrorRow[]): string => {
  const header = ["| Tag | Code | i18n key |", "|---|---|---|"]
  const lines = subset.map((r) => `| \`${r.tag}\` | \`${r.code}\` | \`${r.i18nKey}\` |`)
  return [...header, ...lines].join("\n")
}

const validation = rows.filter((r) => r.severity === "validation")
const domain = rows.filter((r) => r.severity === "domain")
const infrastructure = rows.filter((r) => r.severity === "infrastructure")

const document = [
  "# Error code map",
  "",
  "Generated by `just gen-error-docs` from `packages/core/src/domain/errors/Errors.ts:574`.",
  "Drift-gated: editing this file by hand will fail `just check`. Add a new",
  "`Schema.TaggedErrorClass` to the registry and re-run the generator.",
  "",
  "Every row corresponds to one `_tag` discriminator and projects onto four",
  "downstream surfaces (ADR-0017): the `code`, the `severity`, the `i18nKey`",
  "(`error.<tag>` per `errorToI18nKey`), and the `__typename` of the",
  "`BookingError` GraphQL union arm.",
  "",
  `**Total**: ${String(rows.length)} tags ` +
    `(validation ${String(validation.length)} / ` +
    `domain ${String(domain.length)} / ` +
    `infrastructure ${String(infrastructure.length)}).`,
  "",
  "## Validation",
  "",
  "Recoverable client-input failures. The frontend renders the",
  "`i18nKey` as a short user-facing message via paraglide.",
  "",
  renderTable(validation),
  "",
  "## Domain",
  "",
  "Business-rule refusals reachable only after authentication +",
  "world-snapshot resolution. The operator sees these in the audit",
  "log and the structured access log; the frontend localises them",
  "the same way it does validation errors.",
  "",
  renderTable(domain),
  "",
  "## Infrastructure",
  "",
  "Storage / concurrency / aggregate-not-found failures. The `cause`",
  "preview is permitted only on `Storage` (ADR-0017) and exposed on",
  "the GraphQL response only in dev mode (ADR-0043).",
  "",
  renderTable(infrastructure),
].join("\n")

process.stdout.write(`${document}\n`)
