import { readFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"
import { openApiDocument } from "../../../src/server/http/openapi.js"

/**
 * ADR-0083 — `docs/openapi.json` is the published wire contract.
 * It is generated by `pnpm --filter default run openapi:write` (the
 * `scripts/write-openapi-json.ts` runner) from the in-memory
 * `openApiDocument`. Whenever a developer changes `openapi.ts` /
 * `boundarySchemas.ts` / `openapiRegistry.ts` they must regenerate
 * the artefact, and `apps/web` must regenerate its TypeScript types
 * from it.
 *
 * This test pins the on-disk artefact to the in-memory document so
 * a forgotten regeneration surfaces in CI rather than as a
 * type-error in `apps/web` two PRs later.
 */

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, "../../../../..")
const onDiskPath = resolve(repoRoot, "docs/openapi.json")

describe("ADR-0083 — docs/openapi.json is in sync with in-memory openApiDocument", () => {
  it("re-running `pnpm --filter default run openapi:write` would produce no diff", () => {
    const expected = `${JSON.stringify(openApiDocument, null, 2)}\n`
    const actual = readFileSync(onDiskPath, "utf8")
    if (actual === expected) {
      expect(actual).toBe(expected)
      return
    }
    // Build a small, focused diff hint so the failure message points
    // operators at the regeneration command rather than dumping the
    // 76 KB document into the terminal.
    const hint =
      "docs/openapi.json is stale. Run `pnpm --filter default run openapi:write` " +
      "(then `pnpm --filter web run openapi:gen` to refresh client types)."
    // `expect.fail` with a string halts the assertion chain and prints
    // the hint at the top of the failure report.
    throw new Error(hint)
  })
})
